version: '3.8'

services:
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  backend:
    image: node:16-alpine
    working_dir: /app
    command: npm start
    volumes:
      - ./backend:/app
      - /app/node_modules
    expose:
      - "5000" 